# Use SDK image for building and testing
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy project files and restore dependencies for both app and tests
COPY ["RealTimeAdminPanel/RealTimeAdminPanel.csproj", "RealTimeAdminPanel/"]
COPY ["Tests/IntegrationTests/IntegrationTests.csproj", "Tests/IntegrationTests/"]
COPY ["Tests/UnitTest/UnitTests.csproj", "Tests/UnitTest/"]
RUN dotnet restore "RealTimeAdminPanel/RealTimeAdminPanel.csproj"
RUN dotnet restore "Tests/IntegrationTests/IntegrationTests.csproj"
RUN dotnet restore "Tests/UnitTest/UnitTests.csproj"

# Copy the full source code and build
COPY . .
RUN dotnet build "RealTimeAdminPanel/RealTimeAdminPanel.csproj" -c Release -o /app/build