services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5228:5228"
    volumes:
      - ./:/app
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:5228"