services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing

  tests:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - api
    command: ["dotnet", "test", "--logger:console;verbosity=detailed"]