services:
  api:
    container_name: Web
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5228:5228"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production