name: CI/CD with Docker for .NET Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Check Docker Version
        run: docker --version

      - name: Verify Docker Daemon is Running
        run: docker info

  build:
    runs-on: self-hosted
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Verify Docker Image Build
        run: docker images | grep myapp

  test:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Tests
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/Tests/ myapp:latest dotnet test

  deploy:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy with Docker Compose
        run: docker-compose up -d --build
