name: CI/CD Pipeline for ASP.NET Core with Docker Compose

on:
  push:
    branches:
      - main  # Run pipeline on push to main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t realtimeadminpanel .

  test:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: |
          docker run --rm realtimeadminpanel dotnet test /app/tests/unit/UnitTests.dll --no-build --logger trx

      - name: Run Integration Tests
        run: |
          docker run --rm realtimeadminpanel dotnet test /app/tests/integration/IntegrationTests.dll --no-build --logger trx

  deploy:
    runs-on: self-hosted
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/compose-action@v2

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d