name: CI/CD with Docker for .NET Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Self-hosted runner (Docker on your Mac)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Verify Docker Image Build
        run: docker images | grep myapp

  test:
    runs-on: self-hosted  # Self-hosted runner (Docker on your Mac)
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Run tests for xUnit project
      - name: Run Tests
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/Tests/ myapp:latest dotnet test

  deploy:
    runs-on: self-hosted  # Self-hosted runner (Docker on your Mac)
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Deploy with Docker Compose
        run: docker-compose up -d --build
