name: CI/CD Pipeline for ASP.NET Core with Docker Compose

on:
  push:
    branches:
      - main  # Run pipeline on push to main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t realtimeadminpanel .

  # test:
  #   runs-on: self-hosted
  #   needs: build

  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: Run Unit Tests
  #       run: |
  #         docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from unit-tests

  #     - name: Run Integration Tests
  #       run: |
  #         docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from integration-tests

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Build Docker Compose
        run: |
          docker-compose.prod.yml up -d