name: CI-CD with Docker for .NET application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: |
          docker build -t myapp .  # Build the Docker image

  test:
      runs-on: self-hosted
      needs: build
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
      
        - name: Run Tests in Test Folder
          run: |
            docker run --rm myapp dotnet test  # Run tests

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Build Docker Compose
        run: |
          docker-compose up -d  # Build and start services defined in docker-compose.yml
